"""init_all_tables

Revision ID: f46e333b3e81
Revises: 
Create Date: 2026-05-18 10:24:39.828579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46e333b3e81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('bio', sa.String(length=512), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_assets_current_version_id'), 'role_assets', ['current_version_id'], unique=False)
    op.create_table('knowledge_refs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_object_id', sa.String(length=512), nullable=False),
    sa.Column('knowledge_version_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('knowledge_source', sa.String(length=32), nullable=False),
    sa.Column('bound_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_refs_role_id'), 'knowledge_refs', ['role_id'], unique=False)
    op.create_table('role_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by', sa.String(length=64), nullable=True),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_versions_role_id'), 'role_versions', ['role_id'], unique=False)
    op.create_table('role_version_fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('layer', sa.String(length=4), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['role_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_version_fields_version_id'), 'role_version_fields', ['version_id'], unique=False)
    op.create_table('test_run_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('test_input', sa.Text(), nullable=False),
    sa.Column('test_output', sa.Text(), nullable=False),
    sa.Column('knowledge_retrieved', sa.JSON(), nullable=True),
    sa.Column('human_rating', sa.Integer(), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role_assets.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['role_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_run_records_role_id'), 'test_run_records', ['role_id'], unique=False)
    op.create_table('validated_knowledge_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_object_id', sa.String(length=256), nullable=False),
    sa.Column('knowledge_version_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['role_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validated_knowledge_versions_version_id'), 'validated_knowledge_versions', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validated_knowledge_versions_version_id'), table_name='validated_knowledge_versions')
    op.drop_table('validated_knowledge_versions')
    op.drop_index(op.f('ix_test_run_records_role_id'), table_name='test_run_records')
    op.drop_table('test_run_records')
    op.drop_index(op.f('ix_role_version_fields_version_id'), table_name='role_version_fields')
    op.drop_table('role_version_fields')
    op.drop_index(op.f('ix_role_versions_role_id'), table_name='role_versions')
    op.drop_table('role_versions')
    op.drop_index(op.f('ix_knowledge_refs_role_id'), table_name='knowledge_refs')
    op.drop_table('knowledge_refs')
    op.drop_index(op.f('ix_role_assets_current_version_id'), table_name='role_assets')
    op.drop_table('role_assets')
    # ### end Alembic commands ###
